# Generated by Django 4.0.3 on 2022-03-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarvish_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Char',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=3)),
                ('dwarvish', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
