# Generated by Django 4.0.3 on 2022-03-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarvish_app', '0002_char_delete_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='char',
            name='dwarvish',
            field=models.CharField(max_length=6),
        ),
    ]
