# Generated by Django 4.0.3 on 2022-03-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarvish_app', '0003_alter_char_dwarvish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='char',
            name='dwarvish',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='char',
            name='english',
            field=models.CharField(max_length=10),
        ),
    ]
